# Generated by Django 4.2.11 on 2024-04-30 13:45

import counts.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Countdown', max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('public_link', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=models.SET(counts.models.get_deleted_user_instance), related_name='countdowns', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_countdowns', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(counts.models.get_deleted_user_instance), related_name='updated_countdowns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
