# Generated by Django 4.2.11 on 2024-05-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_add_coutdown_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='dateTime',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
