# Generated by Django 4.2.11 on 2024-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_add_myuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profileImages/'),
        ),
    ]
