# Generated by Django 4.2.13 on 2024-05-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_add_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
