# Generated by Django 4.2.13 on 2024-05-10 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counts', '0004_add_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profileImages/', verbose_name='Profile Image')),
                ('favoriteCountdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counts.countdown')),
                ('followingCountdowns', models.ManyToManyField(blank=True, related_name='followingCountdowns', to='counts.countdown')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
